#!/usr/bin/bash 
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E001-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E002-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E003-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E004-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E005-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E006-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E007-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E008-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E009-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E010-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E011-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E012-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E013-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E014-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E015-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E016-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E017-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E018-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E019-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E020-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E021-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E022-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E023-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E024-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E025-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E026-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E027-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E028-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E029-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E030-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E031-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E032-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E033-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E034-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E035-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E036-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E037-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E038-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E039-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E040-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E041-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E042-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E043-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E044-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E045-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E046-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E047-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E048-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E049-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E050-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E051-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E052-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E053-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E054-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E055-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E056-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E057-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E058-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E059-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E061-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E062-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E063-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E065-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E066-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E067-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E068-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E069-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E070-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E071-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E072-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E073-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E074-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E075-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E076-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E077-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E078-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E079-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E080-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E081-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E082-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E083-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E084-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E085-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E086-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E087-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E088-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E089-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E090-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E091-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E092-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E093-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E094-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E095-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E096-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E097-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E098-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E099-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E100-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E101-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E102-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E103-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E104-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E105-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E106-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E107-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E108-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E109-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E110-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E111-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E112-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E113-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E114-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E115-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E116-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E117-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E118-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E119-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E120-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E121-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E122-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E123-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E124-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E125-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E126-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E127-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E128-H3K27me3.gappedPeak.gz
wget http://egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/gappedPeak/E129-H3K27me3.gappedPeak.gz
